In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("summary.tsv", sep="\t", index_col="sample", dtype={'ST':str, 'Type':str})
df

,source,species,known_resistance_genes_or_PVL,known_MLST_or_Spa-type,validation_area,ST,sequence_type,ref_name,ref_name_local_db,Type,Gene symbol
sample,,,,,,,,,,,
EC3693,Folkhälsomyndigheten,E. coli,OXA-244,ST69,"1, 2, 3",69,69,blaOXA_244.1_KP659189,blaOXA_244,NaN,blaEC
EC3693,Folkhälsomyndigheten,E. coli,OXA-244,ST69,"1, 2, 3",69,69,blaOXA_244.1_KP659189,blaOXA_244,NaN,lpfA
EC3693,Folkhälsomyndigheten,E. coli,OXA-244,ST69,"1, 2, 3",69,69,blaOXA_244.1_KP659189,blaOXA_244,NaN,emrD
EC3693,Folkhälsomyndigheten,E. coli,OXA-244,ST69,"1, 2, 3",69,69,blaOXA_244.1_KP659189,blaOXA_244,NaN,air
EC3693,Folkhälsomyndigheten,E. coli,OXA-244,ST69,"1, 2, 3",69,69,blaOXA_244.1_KP659189,blaOXA_244,NaN,eilA
...,...,...,...,...,...,...,...,...,...,...,...
VR170213,Klinisk mikrobiologi,E. faecium,VanA,NaN,"1, 2",203,203,tet_M_.13_AM990992,VanA_2_M97297,NaN,vanX-A
VR170213,Klinisk mikrobiologi,E. faecium,VanA,NaN,"1, 2",203,203,tet_M_.13_AM990992,VanA_2_M97297,NaN,vanA
VR170213,Klinisk mikrobiologi,E. faecium,VanA,NaN,"1, 2",203,203,tet_M_.13_AM990992,VanA_2_M97297,NaN,vanH-A
VR170213,Klinisk mikrobiologi,E. faecium,VanA,NaN,"1, 2",203,203,tet_M_.13_AM990992,VanA_2_M97297,NaN,vanS-A
VR170213,Klinisk mikrobiologi,E. faecium,VanA,NaN,"1, 2",203,203,tet_M_.13_AM990992,VanA_2_M97297,NaN,vanR-A

In [3]:
validation = pd.read_csv("validation_samples_utf-8.tsv", sep="\t", index_col="sample")
# Change K967 to K967-1
as_list = validation.index.tolist()
idx = as_list.index('K967')
as_list[idx] = 'K967-1'
validation.index = as_list
# Check that the change worked out
validation.loc['K967-1']

source                           Folkhälsomyndigheten
species                                 K. pneumoniae
known_resistance_genes_or_PVL                  OXA-48
known_MLST_or_Spa-type                          ST530
validation_area                               1, 2, 3
Name: K967-1, dtype: object

In [4]:
spaTyper_results = (pd.read_csv("spaTyper.tsv", sep="\t", index_col="sample").drop("species",axis=1)
                    .rename(columns={'Type':'spaType'}))
tseemann_mlst_results = (pd.read_csv("tseemann_mlst.tsv", sep="\t", index_col="sample")
                         .drop("species",axis=1)
                         .rename(columns={'sequence_type':'tseemann_MLST'}))
ariba_mlst_results = (pd.read_csv("ariba_mlst.tsv", sep="\t", index_col="sample")
                         .drop("species",axis=1)
                         .rename(columns={'ST':'ariba_MLST'}))
ariba_local_resistance_DB_results = (pd.read_csv("ariba_local_resistance.tsv", sep="\t", index_col="sample")
                         .drop("species",axis=1)
                         .rename(columns={'ref_name':'ariba_local_resistance_DB'}))
ariba_resfinder_resistance_DB_results = (pd.read_csv("ariba_resfinder_resistance.tsv", sep="\t", index_col="sample")
                         .drop("species",axis=1)
                         .rename(columns={'ref_name':'ariba_resfinder_resistance_DB'}))
aMRFinderPlus_results = (pd.read_csv("aMRFinderPlus.tsv", sep="\t", index_col="sample")
                         .drop("species",axis=1)
                         .rename(columns={'Gene symbol':'aMRFinderPlus'}))
spaTyper_results[spaTyper_results['spaType'].notna()]#.shape[0]

             spaType
sample
HY175301        t001
HY175302        t002
HY176190       t1339
HY176435       t1171
HY176898       t1028
Kontroll-126    t037
PU117379        t528
PY1704946       t437
PY1705269     t16761
PY1707502       t044
SASPA17S-01     t008
SASPA17S-03     t108
SASPA17S-05     t002
SASPA17S-06     t032
HY161669       t1339
HY170721        t386
HY176242        t088
HY177532       t3527
PD171964       t1171
PY1704281       t843
PY1706490       t127
PY1707767       t019
SASPA17S-02     t003
SASPA17S-04     t011
Stam-146        t438
HY170610        t386
HY170908        t386
HY170910        t386
HY171014        t386
HY171211        t386
HY171212        t386
HY175294        t051
HY175295        t004
HY175296        t127
HY175297        t004
HY175298        t009
HY175299        t002
HY175300        t004

In [5]:
ariba_local_resistance_DB = (ariba_local_resistance_DB_results[ariba_local_resistance_DB_results["ariba_local_resistance_DB"].notna()]['ariba_local_resistance_DB']
              .reset_index()
              .drop_duplicates()
              .set_index("sample")
              .groupby(['sample'])['ariba_local_resistance_DB']
              .apply(','.join))
ariba_resfinder_resistance_DB = (ariba_resfinder_resistance_DB_results[ariba_resfinder_resistance_DB_results["ariba_resfinder_resistance_DB"].notna()]['ariba_resfinder_resistance_DB']
              .reset_index()
              .drop_duplicates()
              .set_index("sample")
              .groupby(['sample'])['ariba_resfinder_resistance_DB']
              .apply(','.join))
aMRFinderPlus = (aMRFinderPlus_results[aMRFinderPlus_results["aMRFinderPlus"].notna()]['aMRFinderPlus']
              .reset_index()
              .drop_duplicates()
              .set_index("sample")
              .groupby(['sample'])['aMRFinderPlus']
              .apply(','.join))
ariba_local_resistance_DB

sample
AB164094       blaKPC_2,blaOXA_9,blaSHV_11_7d,blaTEM_1,blaKPC...
EC3693                                                blaOXA_244
EC3712         blaCMY_2,blaOXA_48,blaTEM_1_2d,blaCMY_3,blaTEM...
EC3717                         blaCTX_M_27,blaNDM_1,blaCTX_M_106
EC3718         blaCMY_42,blaCTX_M_15,blaOXA_1,blaCMY_3,blaCTX...
                                     ...
SASPA17S-05                                     mecA_15_AB505628
SASPA17S-06                                      mecA_4_AB033763
Stam-146                                            PVL_HM584708
UO1639842                                      blaCMY_2,blaCMY_3
VR170213                                           VanA_2_M97297
Name: ariba_local_resistance_DB, Length: 81, dtype: object

Write the merged data to tsv

In [6]:
(validation.merge(right=aMRFinderPlus, how="left", left_index=True, right_index=True)
 .merge(right=spaTyper_results, how="left", left_index=True, right_index=True)
 .merge(right=tseemann_mlst_results, how="left", left_index=True, right_index=True)
 .merge(right=ariba_mlst_results, how="left", left_index=True, right_index=True)
 .merge(right=ariba_local_resistance_DB, how="left", left_index=True, right_index=True)
 .merge(right=ariba_resfinder_resistance_DB, how="left", left_index=True, right_index=True)
 .to_csv("all_data.tsv", sep='\t'))